import React,{useEffect,useRef,useState}from'react';
import {useAuth} from '../context/session';
import {supabase} from '../context/../lib/supabase';import{Link,useNavigate}from'react-router-dom';import{motion,AnimatePresence}from'framer-motion';import{GraduationCap,Mail,Lock,ArrowRight,Loader2,KeyRound,ShieldCheck}from'lucide-react';
const OTP_LEN=4;
export default function Auth(){const[isSignUp,setIsSignUp]=useState(false);const[mode,setMode]=useState('password');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[otp,setOtp]=useState(Array(OTP_LEN).fill(''));const[otpSent,setOtpSent]=useState(false);const[errorMsg,setErrorMsg]=useState('');const[message,setMessage]=useState('');const[loading,setLoading]=useState(false);const refs=useRef([]);const{signIn,signUp,requestOtp,verifyOtp}=useAuth();const navigate=useNavigate();
const finish=async()=>{try{const{data:{user}}=await supabase.auth.getUser();if(user){const{data}=await supabase.from('user_settings').select('default_route').eq('user_id',user.id).maybeSingle();navigate(data?.default_route||'/dashboard');return}}catch{}navigate('/dashboard')};
const submitPassword=async e=>{e.preventDefault();setLoading(true);setErrorMsg('');setMessage('');try{if(isSignUp){const{error}=await signUp(email,password);if(error)throw error;setMessage('Account created. Check your email if email confirmation is enabled, then sign in.')}else{const{error}=await signIn(email,password);if(error)throw error;await finish()}}catch(e){setErrorMsg(e.message||'Authentication failed')}finally{setLoading(false)}};
const sendOtp=async()=>{setLoading(true);setErrorMsg('');setMessage('');try{await requestOtp(email,'login');setOtpSent(true);setMessage('If this email belongs to an account, a 4-digit code has been sent by SMTP.')}catch(e){setErrorMsg(e.message)}finally{setLoading(false)}};
const verify=async e=>{e.preventDefault();const code=otp.join('');if(code.length!==OTP_LEN)return setErrorMsg('Enter all 4 digits.');setLoading(true);setErrorMsg('');try{await verifyOtp(email,code,'login');await finish()}catch(e){setErrorMsg(e.message)}finally{setLoading(false)}};
const digit=(i,v)=>{const x=v.replace(/\D/g,'');if(x.length>1){const a=x.slice(0,OTP_LEN).split('');const n=[...otp];a.forEach((d,j)=>{if(i+j<OTP_LEN)n[i+j]=d});setOtp(n);refs.current[Math.min(i+a.length,OTP_LEN-1)]?.focus();return}const n=[...otp];n[i]=x;setOtp(n);if(x&&i<OTP_LEN-1)refs.current[i+1]?.focus()};
useEffect(()=>{setErrorMsg('');setMessage('');setOtpSent(false);setOtp(Array(OTP_LEN).fill(''))},[mode,isSignUp]);
return <div className="min-h-[78vh] grid place-items-center px-4 py-10"><motion.div initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} className="w-full max-w-md overflow-hidden rounded-[2rem] border border-white/60 dark:border-slate-800 bg-white/90 dark:bg-slate-950/85 backdrop-blur-2xl shadow-2xl shadow-indigo-500/10"><div className="h-1.5 bg-gradient-to-r from-indigo-500 via-cyan-400 to-violet-500"/><div className="p-7 sm:p-8"><div className="text-center mb-6"><div className="inline-flex bg-gradient-to-br from-indigo-600 to-cyan-500 p-3 rounded-2xl mb-3 text-white shadow-lg shadow-indigo-500/25"><GraduationCap className="w-7 h-7"/></div><h2 className="text-2xl font-black text-slate-950 dark:text-white">{isSignUp?'Create your account':'Welcome back'}</h2><p className="text-sm text-slate-500 mt-1">{isSignUp?'Build your scholarship command center.':'Password or secure 4-digit email OTP.'}</p></div>
{!isSignUp&&<div className="grid grid-cols-2 gap-2 p-1.5 bg-slate-100 dark:bg-slate-900 rounded-2xl mb-5"><button onClick={()=>setMode('password')} className={`py-2.5 rounded-xl text-sm font-bold ${mode==='password'?'bg-white dark:bg-slate-800 shadow text-indigo-600 dark:text-indigo-300':'text-slate-500'}`}><Lock className="inline w-4 h-4 mr-1"/>Password</button><button onClick={()=>setMode('otp')} className={`py-2.5 rounded-xl text-sm font-bold ${mode==='otp'?'bg-white dark:bg-slate-800 shadow text-indigo-600 dark:text-indigo-300':'text-slate-500'}`}><KeyRound className="inline w-4 h-4 mr-1"/>4-digit OTP</button></div>}
{errorMsg&&<div className="mb-4 p-3 bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 rounded-xl text-rose-600 dark:text-rose-300 text-xs font-semibold">{errorMsg}</div>}{message&&<div className="mb-4 p-3 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 rounded-xl text-emerald-700 dark:text-emerald-300 text-xs font-semibold">{message}</div>}
<AnimatePresence mode="wait">{(isSignUp||mode==='password')?<motion.form key="password" initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} exit={{opacity:0}} onSubmit={submitPassword} className="space-y-4"><Field icon={Mail} type="email" value={email} onChange={setEmail} placeholder="student@university.edu" label="Email address"/><Field icon={Lock} type="password" value={password} onChange={setPassword} placeholder="••••••••" label="Password" minLength={6}/><button disabled={loading} className="w-full py-3.5 bg-gradient-to-r from-indigo-600 to-cyan-600 hover:brightness-110 text-white rounded-xl font-extrabold flex justify-center gap-2 shadow-lg shadow-indigo-500/20">{loading?<Loader2 className="w-5 h-5 animate-spin"/>:<>{isSignUp?'Create account':'Log in'}<ArrowRight className="w-4 h-4"/></>}</button></motion.form>:<motion.form key="otp" initial={{opacity:0,x:8}} animate={{opacity:1,x:0}} exit={{opacity:0}} onSubmit={verify} className="space-y-4"><Field icon={Mail} type="email" value={email} onChange={setEmail} placeholder="student@university.edu" label="Email address"/>{otpSent&&<div className="flex justify-center gap-3 py-2">{otp.map((d,i)=><input key={i} ref={el=>refs.current[i]=el} inputMode="numeric" value={d} maxLength={4} onChange={e=>digit(i,e.target.value)} onKeyDown={e=>{if(e.key==='Backspace'&&!otp[i]&&i>0)refs.current[i-1]?.focus()}} className="w-14 h-14 text-center text-2xl font-black rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 focus:ring-2 focus:ring-indigo-500 outline-none"/>)}</div>}<button type="button" disabled={loading||!email} onClick={sendOtp} className="w-full py-3 rounded-xl border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 font-bold">{otpSent?'Resend 4-digit code':'Send 4-digit code'}</button>{otpSent&&<button disabled={loading} className="w-full py-3.5 bg-gradient-to-r from-indigo-600 to-cyan-600 text-white rounded-xl font-extrabold flex justify-center gap-2">{loading?<Loader2 className="w-5 h-5 animate-spin"/>:<><ShieldCheck className="w-5 h-5"/>Verify & sign in</>}</button>}</motion.form>}</AnimatePresence>
<div className="mt-6 flex items-center justify-between gap-3 text-xs"><button onClick={()=>setIsSignUp(!isSignUp)} className="font-bold text-indigo-600 dark:text-indigo-400 hover:underline">{isSignUp?'Already registered? Log in':'New here? Create account'}</button>{!isSignUp&&<Link to="/reset-password" className="text-slate-500 hover:text-indigo-500">Forgot password?</Link>}</div></div></motion.div></div>}
function Field({icon:Icon,label,value,onChange,...props}){return <label className="block"><span className="block text-xs font-extrabold uppercase tracking-wider text-slate-500 mb-1.5">{label}</span><div className="relative"><Icon className="absolute left-3.5 top-3.5 w-4 h-4 text-slate-400"/><input required value={value} onChange={e=>onChange(e.target.value)} {...props} className="w-full pl-10 pr-4 py-3 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"/></div></label>}
