import React,{useEffect,useRef,useState}from'react';import{KeyRound,Mail,Loader2,Lock,ShieldCheck}from'lucide-react';import {useAuth} from '../context/session';
import {supabase} from '../context/../lib/supabase';
const N=4;
export default function PasswordReset(){const{user,requestOtp,verifyOtp}=useAuth();const[step,setStep]=useState(user?3:1);const[email,setEmail]=useState(user?.email||'');const[otp,setOtp]=useState(Array(N).fill(''));const[pw,setPw]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[msg,setMsg]=useState('');const refs=useRef([]);useEffect(()=>{if(user){setEmail(user.email||'');setStep(3)}},[user]);
const send=async e=>{e.preventDefault();setLoading(true);setError('');setMsg('');try{await requestOtp(email,'reset');setStep(2);setMsg('If the account exists, a 4-digit reset code was sent by SMTP.')}catch(e){setError(e.message)}finally{setLoading(false)}};
const verify=async e=>{e.preventDefault();const code=otp.join('');if(code.length!==N)return setError('Enter all 4 digits.');setLoading(true);setError('');try{await verifyOtp(email,code,'reset');setStep(3);setMsg('Code verified. Set your new password.')}catch(e){setError(e.message)}finally{setLoading(false)}};
const update=async e=>{e.preventDefault();setLoading(true);setError('');try{const{error}=await supabase.auth.updateUser({password:pw});if(error)throw error;setMsg('Password updated successfully.');setTimeout(()=>{window.location.href='/settings'},700)}catch(e){setError(e.message)}finally{setLoading(false)}};
const digit=(i,v)=>{const x=v.replace(/\D/g,'');if(x.length>1){const a=x.slice(0,N).split('');const n=[...otp];a.forEach((d,j)=>{if(i+j<N)n[i+j]=d});setOtp(n);refs.current[Math.min(i+a.length,N-1)]?.focus();return}const n=[...otp];n[i]=x;setOtp(n);if(x&&i<N-1)refs.current[i+1]?.focus()};
return <div className="min-h-[78vh] grid place-items-center p-4"><div className="w-full max-w-md rounded-[2rem] overflow-hidden bg-white/90 dark:bg-slate-950/90 backdrop-blur-2xl border border-slate-200 dark:border-slate-800 shadow-2xl"><div className="h-1.5 bg-gradient-to-r from-cyan-400 via-indigo-500 to-violet-500"/><div className="p-8"><div className="text-center mb-6"><div className="w-12 h-12 bg-indigo-500/10 rounded-2xl grid place-items-center mx-auto mb-3 text-indigo-500">{step===3?<Lock/>:<KeyRound/>}</div><h1 className="text-2xl font-black text-slate-950 dark:text-white">{step===1?'Reset password':step===2?'Verify 4-digit code':'Choose new password'}</h1><p className="text-sm text-slate-500 mt-1">{step===1?'We will send a short-lived code by SMTP.':step===2?`Code sent to ${email}`:'Use at least 8 characters.'}</p></div>{error&&<Notice bad>{error}</Notice>}{msg&&<Notice>{msg}</Notice>}
{step===1&&<form onSubmit={send} className="space-y-4"><div className="relative"><Mail className="absolute left-3.5 top-3.5 w-4 h-4 text-slate-400"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" className="input-modern pl-10"/></div><button disabled={loading} className="primary-modern">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:'Send 4-digit OTP'}</button></form>}
{step===2&&<form onSubmit={verify} className="space-y-5"><div className="flex justify-center gap-3">{otp.map((d,i)=><input key={i} ref={el=>refs.current[i]=el} inputMode="numeric" value={d} maxLength={4} onChange={e=>digit(i,e.target.value)} className="w-14 h-14 rounded-2xl text-center text-2xl font-black bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 focus:ring-2 focus:ring-indigo-500 outline-none"/>)}</div><button disabled={loading} className="primary-modern">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<><ShieldCheck className="w-4 h-4"/>Verify code</>}</button><button type="button" onClick={()=>requestOtp(email,'reset').then(()=>setMsg('A fresh code was sent.')).catch(e=>setError(e.message))} className="w-full text-xs font-bold text-indigo-500">Resend code</button></form>}
{step===3&&<form onSubmit={update} className="space-y-4"><input required minLength={8} type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="New password" className="input-modern"/><button disabled={loading} className="primary-modern">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:'Update password'}</button></form>}</div></div></div>}
function Notice({children,bad}){return <div className={`mb-4 p-3 rounded-xl text-xs font-semibold border ${bad?'bg-rose-50 border-rose-200 text-rose-700 dark:bg-rose-950/30 dark:border-rose-900 dark:text-rose-300':'bg-emerald-50 border-emerald-200 text-emerald-700 dark:bg-emerald-950/30 dark:border-emerald-900 dark:text-emerald-300'}`}>{children}</div>}
