import { invokeFunction } from '../lib/functions';
import { notify } from '../lib/notify';
import React, { useEffect, useState } from 'react';
import { Check, Loader2, ShieldCheck, Sparkles, Building2 } from 'lucide-react';
import {useAuth} from '../context/session';
import {supabase} from '../context/../lib/supabase';

const featureLabels = {
  advanced_matching: 'Explainable advanced matching', instant_alerts: 'Instant change/deadline alerts', application_studio: 'AI Application Studio', counselor_workspace: 'Counselor workspace', campaigns: 'Sponsored campaign tools', lead_analytics: 'Lead analytics'
};

export default function Pricing() {
  const { user } = useAuth(); const [plans,setPlans]=useState([]); const [sub,setSub]=useState(null); const [usage,setUsage]=useState(0); const [busy,setBusy]=useState('');
  useEffect(()=>{(async()=>{const {data:p}=await supabase.from('plans').select('*').eq('active',true).order('monthly_ai_credits');setPlans(p||[]);if(user){const {data:s}=await supabase.from('subscriptions').select('*').eq('user_id',user.id).maybeSingle();setSub(s);const start=new Date();start.setUTCDate(1);start.setUTCHours(0,0,0,0);const {data:u}=await supabase.from('ai_usage').select('credit_cost').eq('user_id',user.id).gte('created_at',start.toISOString());setUsage((u||[]).reduce((a,x)=>a+Number(x.credit_cost||0),0));}})()},[user]);
  const checkout=async(planId)=>{if(!user){location.href='/auth';return;}setBusy(planId);try{const {data,error}=await invokeResult('billing-checkout',{body:{planId}});if(error||data?.error)throw new Error(data?.error||error.message);location.href=data.url;}catch(e){notify(e.message)}finally{setBusy('')}};
  const portal=async()=>{setBusy('portal');try{const {data,error}=await invokeResult('billing-portal',{body:{}});if(error||data?.error)throw new Error(data?.error||error.message);location.href=data.url;}catch(e){notify(e.message)}finally{setBusy('')}};
  return <div className="max-w-6xl mx-auto space-y-8 pb-12"><div className="text-center space-y-3"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-500 text-sm font-bold"><ShieldCheck className="w-4 h-4"/>Verified discovery stays free</div><h1 className="text-4xl font-black text-slate-900 dark:text-white">Pay for automation, not access to scholarship links.</h1><p className="text-slate-500 dark:text-slate-400">Upgrade for deeper matching, application automation, monitoring and team workflows.</p>{sub&&<p className="text-sm font-semibold text-indigo-500">Current plan: {sub.plan_id} · {usage} AI credits used this month</p>}</div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{plans.map(p=><div key={p.id} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 flex flex-col"><div className="flex items-center gap-2 mb-3">{p.audience==='business'?<Building2 className="w-5 h-5 text-indigo-500"/>:<Sparkles className="w-5 h-5 text-indigo-500"/>}<h2 className="text-xl font-extrabold text-slate-900 dark:text-white">{p.name}</h2></div><p className="text-2xl font-bold mb-3">{p.id==='free'?'Free':p.price_amount!=null?`${new Intl.NumberFormat(undefined,{style:'currency',currency:p.price_currency||'USD'}).format(p.price_amount)} / ${p.billing_interval||'month'}`:'Pricing coming soon'}</p><p className="text-sm text-slate-500 mb-4">{p.monthly_ai_credits} AI credits/month · {p.max_watchlists} watchlists</p><div className="space-y-2 flex-1">{Object.entries(p.features||{}).filter(([,v])=>v).map(([k])=><div key={k} className="flex gap-2 text-sm text-slate-600 dark:text-slate-300"><Check className="w-4 h-4 text-emerald-500 shrink-0"/>{featureLabels[k]||k}</div>)}</div>{p.id==='free'?<button disabled className="mt-6 rounded-xl py-2.5 font-bold bg-slate-100 dark:bg-slate-800 text-slate-500">Free</button>:sub?.plan_id===p.id?<button onClick={portal} disabled={busy==='portal'} className="mt-6 rounded-xl py-2.5 font-bold bg-slate-900 dark:bg-white text-white dark:text-slate-900">{busy==='portal'?<Loader2 className="w-4 h-4 animate-spin mx-auto"/>:'Manage billing'}</button>:<button onClick={()=>checkout(p.id)} disabled={!!busy||p.price_amount==null} className="mt-6 rounded-xl py-2.5 font-bold bg-indigo-600 text-white hover:bg-indigo-500">{busy===p.id?<Loader2 className="w-4 h-4 animate-spin mx-auto"/>:`Choose ${p.name}`}</button>}</div>)}</div><p className="text-xs text-center text-slate-500">Review the price and renewal terms before checkout. Any sponsored or partner relationship is disclosed before sharing your information.</p></div>;
}

async function invokeResult(name,options){try{return {data:await invokeFunction(name,options),error:null};}catch(error){return {data:null,error};}}
