import { invokeFunction } from '../lib/functions';
import { notify } from '../lib/notify';
import React, { useEffect, useState } from 'react';
import { Activity, CheckCircle2, ExternalLink, Loader2, RefreshCw, ShieldAlert, XCircle } from 'lucide-react';

export default function Quality() {
  const [data, setData] = useState({ queue:[], runs:[], events:[], referrals:[], sponsorAccounts:[], campaigns:[] });
  const [loading,setLoading] = useState(true); const [refreshing,setRefreshing]=useState(false); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [actionError,setActionError]=useState('');
  const load = async ({initial=false}={}) => { if(initial)setLoading(true);else setRefreshing(true); setError(''); try { const { data: result, error: fnError } = await invokeResult('quality-admin', { method:'GET' }); if (fnError || result?.error) throw new Error(result?.error || fnError.message); setData(result); } catch(e){ setError(e.message); } finally { setLoading(false);setRefreshing(false); } };
  useEffect(()=>{ load(); },[]);
  const act = async (action,id,extra={}) => { const actionKey=`${action}:${id}`;setBusy(actionKey);setActionError('');try { const {data:result,error:fnError}=await invokeResult('quality-admin',{body:{action,id,...extra}}); if(fnError||result?.error) throw new Error(result?.error||fnError.message); setData(current=>({...current,queue:current.queue.filter(item=>item.id!==id)}));notify(action==='approve'?'Opportunity approved and published.':'Opportunity rejected.'); } catch(e){ setActionError(e.message);notify(e.message); } finally { setBusy(''); } };
  if (loading) return <div className="h-[60vh] grid place-items-center"><Loader2 className="w-8 h-8 animate-spin text-indigo-500"/></div>;
  if (error) return <div className="max-w-3xl mx-auto p-6 rounded-2xl border border-rose-500/30 bg-rose-500/10"><ShieldAlert className="w-8 h-8 text-rose-500 mb-3"/><h1 className="text-xl font-black">Quality Console unavailable</h1><p className="text-sm mt-2 text-slate-600 dark:text-slate-300">{error}</p><p className="text-xs mt-3 text-slate-500">Only users with auth app_metadata role “admin” or “staff” can access this server-side console.</p></div>;
  return <div className="max-w-7xl mx-auto space-y-8 pb-12">
    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4"><div><h1 className="text-3xl font-black text-slate-900 dark:text-white">Trust & Quality Console</h1><p className="text-slate-500">Human review for candidates scoring 70 or below, agent failures and disclosed program referrals.</p></div><button disabled={refreshing} onClick={()=>load()} className="h-10 px-4 rounded-xl bg-slate-100 dark:bg-slate-800 font-bold flex items-center justify-center gap-2"><RefreshCw className={`w-4 h-4 ${refreshing?'animate-spin':''}`}/>Refresh</button></div>
    {actionError&&<div role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-700 dark:text-rose-300">Review action failed: {actionError}. You can retry this item; other review buttons remain available.</div>}
    <section><h2 className="font-extrabold text-slate-900 dark:text-white mb-3">Pending opportunity review ({data.queue.length})</h2><div className="space-y-3">{data.queue.length===0?<p className="text-sm text-slate-500 p-5 rounded-xl border border-dashed border-slate-300 dark:border-slate-700">No candidates scoring 70 or below are waiting for review.</p>:data.queue.map(item=>{const approving=busy===`approve:${item.id}`;const rejecting=busy===`reject:${item.id}`;return <div key={item.id} className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div className="min-w-0"><div className="text-xs font-bold text-amber-600">Verification score {item.verification_score}% · Manual decision required</div><h3 className="font-extrabold text-lg text-slate-900 dark:text-white mt-1">{item.candidate_data?.title || item.search_title || 'Untitled candidate'}</h3><p className="text-sm text-slate-500">{item.candidate_data?.organization || 'Organization not extracted'} · {item.candidate_data?.country || 'Country not extracted'} · deadline {item.candidate_data?.deadline || 'Unknown'}</p><a href={item.source_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm text-indigo-500 mt-2 break-all"><ExternalLink className="w-4 h-4 shrink-0"/>Inspect source before deciding</a><details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer font-bold">Checks & extracted data</summary><pre className="mt-2 whitespace-pre-wrap overflow-auto max-h-64 p-3 rounded-lg bg-slate-100 dark:bg-slate-950">{JSON.stringify({checks:item.checks,candidate:item.candidate_data},null,2)}</pre></details></div><div className="flex flex-wrap gap-2 shrink-0"><button disabled={Boolean(busy)} onClick={()=>act('approve',item.id)} className="px-3 py-2 rounded-xl bg-emerald-600 text-white font-bold flex items-center gap-1">{approving?<Loader2 className="w-4 h-4 animate-spin"/>:<CheckCircle2 className="w-4 h-4"/>}{approving?'Approving…':'Approve'}</button><button disabled={Boolean(busy)} onClick={()=>act('reject',item.id)} className="px-3 py-2 rounded-xl bg-rose-500/10 text-rose-600 font-bold flex items-center gap-1">{rejecting?<Loader2 className="w-4 h-4 animate-spin"/>:<XCircle className="w-4 h-4"/>}{rejecting?'Rejecting…':'Reject'}</button></div></div></div>})}</div></section>
    <section className="grid lg:grid-cols-2 gap-5"><div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5"><h2 className="font-extrabold flex items-center gap-2"><Activity className="w-5 h-5 text-indigo-500"/>Recent agent runs</h2><div className="mt-4 space-y-2">{data.runs.map(r=><div key={r.id} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950 text-sm"><div className="flex justify-between"><strong>{r.agent_name}</strong><span className={r.status==='success'?'text-emerald-600':'text-rose-500'}>{r.status}</span></div><p className="text-xs text-slate-500 mt-1">{r.started_at ? new Date(r.started_at).toLocaleString() : ''}</p>{r.error&&<p className="text-xs text-rose-500 mt-1">{r.error}</p>}</div>)}</div></div><div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5"><h2 className="font-extrabold">Warnings & errors</h2><div className="mt-4 space-y-2">{data.events.map(e=><div key={e.id} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950"><p className="text-xs font-bold uppercase text-amber-600">{e.agent_name} · {e.level}</p><p className="text-sm mt-1">{e.message}</p></div>)}</div></div></section>
    <section className="grid lg:grid-cols-2 gap-5"><div><h2 className="font-extrabold mb-3">Sponsor verification ({data.sponsorAccounts?.length || 0})</h2><div className="space-y-3">{(data.sponsorAccounts||[]).map(a=><div key={a.id} className="p-4 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><p className="font-bold">{a.organization_name}</p><p className="text-xs text-slate-500">{a.website || 'No website supplied'}</p><div className="mt-3 flex gap-2"><button onClick={()=>act('sponsor_verify',a.id,{verified:true})} className="px-3 py-1.5 rounded-lg bg-emerald-600 text-white text-xs font-bold">Verify sponsor</button><button onClick={()=>act('sponsor_verify',a.id,{verified:false})} className="px-3 py-1.5 rounded-lg bg-slate-100 dark:bg-slate-800 text-xs font-bold">Keep pending</button></div></div>)}</div></div><div><h2 className="font-extrabold mb-3">Campaign review ({data.campaigns?.length || 0})</h2><div className="space-y-3">{(data.campaigns||[]).map(c=><div key={c.id} className="p-4 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><p className="text-xs font-bold text-indigo-500">{c.sponsor_accounts?.organization_name} {c.sponsor_accounts?.verified?'· verified':'· sponsor pending'}</p><p className="font-bold mt-1">{c.title}</p><a href={c.destination_url} target="_blank" rel="noreferrer" className="text-xs text-indigo-500">Review landing page</a><div className="mt-3 flex gap-2"><button onClick={()=>act('campaign_status',c.id,{status:'active'})} className="px-3 py-1.5 rounded-lg bg-indigo-600 text-white text-xs font-bold">Activate</button><button onClick={()=>act('campaign_status',c.id,{status:'rejected'})} className="px-3 py-1.5 rounded-lg bg-rose-500/10 text-rose-600 text-xs font-bold">Reject</button></div></div>)}</div></div></section>
    <section><h2 className="font-extrabold mb-3">Pending disclosed program referrals ({data.referrals.length})</h2><div className="grid md:grid-cols-2 gap-3">{data.referrals.map(r=><div key={r.id} className="p-4 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><p className="font-bold">{r.programs?.institution} — {r.programs?.title}</p><p className="text-xs text-slate-500 mt-1">Consent recorded {new Date(r.created_at).toLocaleString()}</p><div className="flex gap-2 mt-3"><button onClick={()=>act('referral_status',r.id,{status:'sent'})} className="px-3 py-1.5 rounded-lg bg-indigo-600 text-white text-xs font-bold">Mark sent</button><button onClick={()=>act('referral_status',r.id,{status:'declined'})} className="px-3 py-1.5 rounded-lg bg-slate-100 dark:bg-slate-800 text-xs font-bold">Decline</button></div></div>)}</div></section>
  </div>;
}

async function invokeResult(name,options){try{return {data:await invokeFunction(name,options),error:null};}catch(error){return {data:null,error};}}
