import { notify } from '../lib/notify';
import React,{useEffect,useState}from'react';
import{Building2,Plus,Users,BarChart3,ExternalLink,ShieldCheck,LockKeyhole}from'lucide-react';
import{Link}from'react-router-dom';
import {useAuth} from '../context/session';
import {supabase} from '../context/../lib/supabase';

const empty={title:'',description:'',destination_url:'',target_countries:'',target_fields:'',target_levels:'',budget_cents:0};
const LEAD_STATUSES=['new','reviewed','contacted','qualified','applied','enrolled','rejected'];

export default function SponsorWorkspace(){
  const{user}=useAuth();const[account,setAccount]=useState(null);const[campaigns,setCampaigns]=useState([]);const[leads,setLeads]=useState([]);const[form,setForm]=useState(empty);const[plan,setPlan]=useState('free');
  const load=async()=>{const{data:sub}=await supabase.from('subscriptions').select('plan_id,status').eq('user_id',user.id).maybeSingle();setPlan(['active','trialing'].includes(sub?.status)?sub.plan_id:'free');const{data:a}=await supabase.from('sponsor_accounts').select('*').eq('owner_user_id',user.id).maybeSingle();setAccount(a);setCampaigns([]);setLeads([]);if(a){const{data:c}=await supabase.from('sponsor_campaigns').select('*').eq('sponsor_account_id',a.id).order('created_at',{ascending:false});setCampaigns(c||[]);if(c?.length){const ids=c.map(x=>x.id);const{data:l}=await supabase.from('campaign_leads').select('id,campaign_id,match_score,status,lead_data,created_at,updated_at').in('campaign_id',ids).order('created_at',{ascending:false});setLeads(l||[])}}};
  useEffect(()=>{if(user)load()},[user]); // eslint-disable-line react-hooks/exhaustive-deps
  const createAccount=async()=>{if(plan!=='sponsor')return notify('The Sponsor plan is required to create an organization account.');const name=prompt('Organization name');if(!name)return;const website=prompt('Official organization website (recommended for verification)')||null;const{error}=await supabase.from('sponsor_accounts').insert({owner_user_id:user.id,organization_name:name,website});if(error)notify(error.message);else load()};
  const createCampaign=async e=>{e.preventDefault();const payload={sponsor_account_id:account.id,title:form.title,description:form.description,destination_url:form.destination_url,target_countries:form.target_countries.split(',').map(x=>x.trim()).filter(Boolean),target_fields:form.target_fields.split(',').map(x=>x.trim()).filter(Boolean),target_levels:form.target_levels.split(',').map(x=>x.trim()).filter(Boolean),budget_cents:Number(form.budget_cents||0),status:'review'};const{error}=await supabase.from('sponsor_campaigns').insert(payload);if(error)notify(error.message);else{setForm(empty);load()}};
  const updateLead=async(lead,status)=>{const{error}=await supabase.from('campaign_leads').update({status,updated_at:new Date().toISOString()}).eq('id',lead.id);if(error)notify(error.message);else setLeads(prev=>prev.map(x=>x.id===lead.id?{...x,status}:x))};
  const leadCount=id=>leads.filter(l=>l.campaign_id===id).length;const qualified=id=>leads.filter(l=>l.campaign_id===id&&['qualified','applied','enrolled'].includes(l.status)).length;
  return <div className="space-y-7"><div><h1 className="text-3xl font-black text-slate-900 dark:text-white">Sponsor Campaigns</h1><p className="text-slate-500">Reach opted-in students by eligibility. Only campaign-specific consented profile fields are visible to sponsors.</p></div>
    {!account?<div className="space-y-4">{plan!=='sponsor'&&<div className="p-5 rounded-2xl border border-amber-500/30 bg-amber-500/10"><div className="flex gap-2 font-extrabold text-amber-700 dark:text-amber-300"><LockKeyhole className="w-5 h-5"/>Sponsor plan required</div><p className="text-sm text-slate-600 dark:text-slate-300 mt-2">Choose a Sponsor plan to create campaigns and manage consented leads.</p><Link to="/pricing" className="inline-block mt-3 px-4 py-2 rounded-xl bg-indigo-600 text-white font-bold">View plans</Link></div>}<button disabled={plan!=='sponsor'} onClick={createAccount} className="px-5 py-3 bg-indigo-600 text-white rounded-xl font-bold flex gap-2"><Building2 className="w-5 h-5"/>Create sponsor account</button></div>:<>
      <div className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row sm:justify-between gap-3"><div><p className="text-xs uppercase font-bold text-slate-500">Sponsor</p><h2 className="text-xl font-extrabold text-slate-900 dark:text-white">{account.organization_name}</h2>{account.website&&<a className="text-xs text-indigo-600 dark:text-indigo-300" href={account.website} target="_blank" rel="noreferrer">{account.website}</a>}</div><span className={`self-start px-3 py-1 rounded-full text-xs font-bold ${account.verified?'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300':'bg-amber-500/10 text-amber-700 dark:text-amber-300'}`}>{account.verified?'Verified':'Verification pending'}</span></div>
      <form onSubmit={createCampaign} className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 grid md:grid-cols-2 gap-3"><h2 className="md:col-span-2 font-extrabold text-slate-900 dark:text-white flex gap-2"><Plus className="w-5 h-5"/>New campaign</h2>{['title','destination_url','target_countries','target_fields','target_levels','budget_cents'].map(k=><input key={k} required={['title','destination_url'].includes(k)} type={k==='budget_cents'?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k.replaceAll('_',' ')+(k.startsWith('target_')?' (comma separated)':'')} className="px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700"/>)}<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Campaign description" className="md:col-span-2 px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700"/><button className="md:col-span-2 px-4 py-2.5 rounded-xl bg-indigo-600 text-white font-bold">Submit campaign for review</button></form>
      <div className="grid gap-4">{campaigns.map(c=><section key={c.id} className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-extrabold text-slate-900 dark:text-white">{c.title}</h3><p className="text-sm text-slate-500">Status: {c.status}</p></div><a href={c.destination_url} target="_blank" rel="noreferrer" aria-label="Open campaign destination"><ExternalLink className="w-4 h-4"/></a></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><Metric icon={Users} label="Consented leads" value={leadCount(c.id)}/><Metric icon={ShieldCheck} label="Qualified+" value={qualified(c.id)}/><Metric icon={BarChart3} label="Campaign budget" value={`$${(Number(c.budget_cents||0)/100).toFixed(0)}`}/><Metric icon={Building2} label="Audience" value={[...(c.target_levels||[]),...(c.target_fields||[])].slice(0,2).join(', ')||'Broad'}/></div>
        <div className="mt-5 space-y-3">{leads.filter(l=>l.campaign_id===c.id).map(l=><LeadCard key={l.id} lead={l} updateLead={updateLead}/>)}{!leadCount(c.id)&&<p className="text-sm text-slate-500 rounded-xl border border-dashed border-slate-300 dark:border-slate-700 p-4">No students have explicitly shared profile data with this campaign yet.</p>}</div>
      </section>)}</div>
    </>}
  </div>;
}
function Metric({icon:Icon,label,value}){return <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800 min-w-0"><Icon className="w-4 h-4 text-indigo-500"/><div className="text-lg font-black text-slate-900 dark:text-white mt-1 truncate">{value}</div><div className="text-xs text-slate-500">{label}</div></div>}
function LeadCard({lead,updateLead}){const entries=Object.entries(lead.lead_data||{}).filter(([,v])=>v!=null&&v!=='');return <div className="rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 p-4"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="font-extrabold text-slate-900 dark:text-white">Consented lead {lead.match_score!=null?`· ${lead.match_score}% match`:''}</p><p className="text-xs text-slate-500">Shared {new Date(lead.created_at).toLocaleString()}</p></div><select value={lead.status} onChange={e=>updateLead(lead,e.target.value)} className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-2.5 py-2 text-sm">{LEAD_STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select></div><dl className="grid md:grid-cols-2 gap-x-5 gap-y-2 mt-3">{entries.map(([k,v])=><div key={k} className="min-w-0"><dt className="text-[10px] uppercase tracking-wide font-black text-slate-400">{k.replaceAll('_',' ')}</dt><dd className="text-sm text-slate-700 dark:text-slate-200 break-words">{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></div>}
